---
- name: Deleting AS3 
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"

  tasks:

    - name: AS3 delete via ATC
      include_role:
        name: atc_deploy
      vars:
        atc_method: DELETE
        # Select the service as AS3, Device, or Telemetry
        atc_service: AS3
        as3_tenant: WorkshopExample
        provider:
          server: "{{ ansible_host }}"
          server_port: "443"
          user: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
          validate_certs: "false"
          auth_provider: tmos


