---
- name: LINKLIGHT AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"

  tasks:
    - name: CREATE AS3 definition
      set_fact: 
        as3_definition: "{{ lookup('template', 'j2/as3_definition.j2', split_lines=False) }}" 


    - name: ATC Check AS3 connection
      include_role:
        name: atc_deploy
      vars:
        atc_method: POST
        atc_declaration: "{{ as3_definition }}"
        # Select the service as AS3, Device, or Telemetry
        atc_service: AS3
        provider:
          server: "{{ ansible_host }}"
          server_port: "443"
          user: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
          validate_certs: "false"
          auth_provider: tmos

    - debug: var=atc_AS3_status
